
export const GEN_TESTING_UPDATE_REQUEST = 'GEN_TESTING_UPDATE_REQUEST';
export const GEN_TESTING_UPDATE_SUCCESS = 'GEN_TESTING_UPDATE_SUCCESS';
export const GEN_TESTING_UPDATE_FAILURE = 'GEN_TESTING_UPDATE_FAILURE';
export const GEN_TESTING_FIND_ONE_REQUEST = 'GEN_TESTING_FIND_ONE_REQUEST';
export const GEN_TESTING_FIND_ONE_SUCCESS = 'GEN_TESTING_FIND_ONE_SUCCESS';
export const GEN_TESTING_FIND_ONE_FAILURE = 'GEN_TESTING_FIND_ONE_FAILURE';
